import { configure } from '@gtbuchanan/eslint-config';

export default [
  ...await configure({
    // Skills here target Claude Code, whose frontmatter extends the bare
    // Agent Skills spec (the building blocks use `user-invocable: false`).
    agentSkillsHost: 'claude-code',
    tsconfigRootDir: import.meta.dirname,
  }),
  {
    files: ['skills/*/SKILL.md'],
    rules: {
      /*
       * Eval coverage is the promptfoo suite in evals/<name>/, which lives
       * outside the skill so it is never distributed (see CONTRIBUTING.md).
       * That leaves skills/<name>/evals/evals.json free for the spec's
       * declarative evals; until some skill ships one, this stays off.
       */
      'agent-skills/min-evals': 'off',
    },
  },
  {
    /*
     * Git-ignored, generated directories that the shared config's default
     * ignore list doesn't cover: the per-agent deploy mirrors regenerated by
     * `pnpm skills:sync` and the promptfoo eval-result artifacts. Linting them
     * only surfaces tsconfig parsing errors and Prettier noise on files we
     * don't author.
     */
    ignores: ['.agents/skills/**', '.claude/skills/**', 'artifacts/**'],
  },
];
