import { configure } from '@gtbuchanan/eslint-config';

export default [
  ...await configure({
    // Skills here target Claude Code, whose frontmatter extends the bare
    // Agent Skills spec (the building blocks use `user-invocable: false`).
    agentSkillsHost: 'claude-code',
    tsconfigRootDir: import.meta.dirname,
  }),
  {
    /*
     * Scripts a skill ships sit outside every tsconfig `include`: the root one
     * is generated by `gtb sync` from a fixed list, and a tsconfig inside the
     * skill would be copied to consumers along with it. Without a project the
     * type-aware rules cannot parse the file at all, so it gets an inferred
     * one instead.
     *
     * Set globally rather than against `files`, because typescript-eslint
     * builds one project service per run: a later block that narrows it to
     * some paths arrives after the service exists and is ignored.
     */
    languageOptions: {
      parserOptions: {
        projectService: { allowDefaultProject: ['skills/*/scripts/*.ts'] },
      },
    },
  },
  {
    files: ['skills/*/SKILL.md'],
    rules: {
      /*
       * Eval coverage is the promptfoo suite in evals/<name>/, which lives
       * outside the skill so it is never distributed (see CONTRIBUTING.md).
       * That leaves skills/<name>/evals/evals.json free for the spec's
       * declarative evals; until some skill ships one, this stays off.
       */
      'agent-skills/min-evals': 'off',
    },
  },
  {
    /*
     * Git-ignored, generated directories that the shared config's default
     * ignore list doesn't cover: the per-agent deploy mirrors regenerated by
     * `pnpm skills:sync` and the promptfoo eval-result artifacts. Linting them
     * only surfaces tsconfig parsing errors and Prettier noise on files we
     * don't author.
     */
    ignores: ['.agents/skills/**', '.claude/skills/**', 'artifacts/**'],
  },
];
